DFRobotMaqueenPlus.I2CInit()
basic.forever(function () {
    DFRobotMaqueenPlus.setRGBLight(RGBLight.RGBL, Color.CYAN)
    basic.pause(850)
    DFRobotMaqueenPlus.setRGBLight(RGBLight.RGBL, Color.OFF)
    DFRobotMaqueenPlus.setRGBLight(RGBLight.RGBR, Color.YELLOW)
    basic.pause(850)
    DFRobotMaqueenPlus.setRGBLight(RGBLight.RGBR, Color.OFF)
    DFRobotMaqueenPlus.setRGBLight(RGBLight.RGBL, Color.PINK)
    basic.pause(850)
    DFRobotMaqueenPlus.setRGBLight(RGBLight.RGBL, Color.OFF)
    DFRobotMaqueenPlus.setRGBLight(RGBLight.RGBR, Color.GREEN)
    basic.pause(850)
    DFRobotMaqueenPlus.setRGBLight(RGBLight.RGBR, Color.OFF)
    DFRobotMaqueenPlus.setRGBLight(RGBLight.RGBL, Color.CYAN)
    basic.pause(850)
    DFRobotMaqueenPlus.setRGBLight(RGBLight.RGBL, Color.OFF)
    DFRobotMaqueenPlus.setRGBLight(RGBLight.RGBR, Color.YELLOW)
    basic.pause(850)
    DFRobotMaqueenPlus.setRGBLight(RGBLight.RGBR, Color.OFF)
    DFRobotMaqueenPlus.setRGBLight(RGBLight.RGBL, Color.PINK)
    basic.pause(850)
    DFRobotMaqueenPlus.setRGBLight(RGBLight.RGBL, Color.OFF)
    DFRobotMaqueenPlus.setRGBLight(RGBLight.RGBR, Color.GREEN)
    basic.pause(850)
    DFRobotMaqueenPlus.setRGBLight(RGBLight.RGBR, Color.OFF)
    DFRobotMaqueenPlus.setRGBLight(RGBLight.RGBL, Color.CYAN)
    basic.pause(850)
    DFRobotMaqueenPlus.setRGBLight(RGBLight.RGBL, Color.OFF)
    DFRobotMaqueenPlus.setRGBLight(RGBLight.RGBR, Color.YELLOW)
    basic.pause(850)
    DFRobotMaqueenPlus.setRGBLight(RGBLight.RGBR, Color.OFF)
    DFRobotMaqueenPlus.setRGBLight(RGBLight.RGBL, Color.PINK)
    basic.pause(850)
    DFRobotMaqueenPlus.setRGBLight(RGBLight.RGBL, Color.OFF)
    DFRobotMaqueenPlus.setRGBLight(RGBLight.RGBR, Color.GREEN)
    basic.pause(850)
    DFRobotMaqueenPlus.setRGBLight(RGBLight.RGBR, Color.OFF)
    DFRobotMaqueenPlus.setRGBLight(RGBLight.RGBL, Color.CYAN)
    basic.pause(850)
    DFRobotMaqueenPlus.setRGBLight(RGBLight.RGBL, Color.OFF)
    DFRobotMaqueenPlus.setRGBLight(RGBLight.RGBR, Color.YELLOW)
    basic.pause(850)
    DFRobotMaqueenPlus.setRGBLight(RGBLight.RGBR, Color.OFF)
    DFRobotMaqueenPlus.setRGBLight(RGBLight.RGBL, Color.WHITH)
    basic.pause(850)
    DFRobotMaqueenPlus.setRGBLight(RGBLight.RGBL, Color.OFF)
    basic.pause(1000000000)
})
basic.forever(function () {
    DFRobotMaqueenPlus.mototRun(Motors.ALL, Dir.CW, 30)
    basic.pause(1000)
    DFRobotMaqueenPlus.mototStop(Motors.ALL)
    DFRobotMaqueenPlus.mototRun(Motors.M1, Dir.CW, 30)
    DFRobotMaqueenPlus.mototRun(Motors.M2, Dir.CCW, 25)
    basic.pause(2500)
    DFRobotMaqueenPlus.mototStop(Motors.ALL)
    DFRobotMaqueenPlus.mototRun(Motors.M1, Dir.CCW, 25)
    DFRobotMaqueenPlus.mototRun(Motors.M2, Dir.CW, 30)
    basic.pause(2500)
    DFRobotMaqueenPlus.mototStop(Motors.ALL)
    DFRobotMaqueenPlus.mototRun(Motors.ALL, Dir.CW, 40)
    basic.pause(1000)
    DFRobotMaqueenPlus.mototStop(Motors.ALL)
    DFRobotMaqueenPlus.mototRun(Motors.M1, Dir.CW, 40)
    DFRobotMaqueenPlus.mototRun(Motors.M1, Dir.CW, 30)
    basic.pause(1100)
    DFRobotMaqueenPlus.mototStop(Motors.ALL)
    DFRobotMaqueenPlus.mototRun(Motors.ALL, Dir.CCW, 40)
    basic.pause(500)
    DFRobotMaqueenPlus.mototRun(Motors.M2, Dir.CW, 30)
    DFRobotMaqueenPlus.mototRun(Motors.M1, Dir.CCW, 30)
    basic.pause(500)
    DFRobotMaqueenPlus.mototRun(Motors.ALL, Dir.CCW, 40)
    basic.pause(500)
    DFRobotMaqueenPlus.mototRun(Motors.M1, Dir.CW, 30)
    DFRobotMaqueenPlus.mototRun(Motors.M2, Dir.CCW, 30)
    basic.pause(500)
    DFRobotMaqueenPlus.mototRun(Motors.ALL, Dir.CCW, 40)
    basic.pause(500)
    DFRobotMaqueenPlus.mototRun(Motors.M2, Dir.CW, 30)
    DFRobotMaqueenPlus.mototRun(Motors.M1, Dir.CCW, 30)
    basic.pause(500)
    DFRobotMaqueenPlus.mototRun(Motors.ALL, Dir.CCW, 40)
    basic.pause(1000)
    DFRobotMaqueenPlus.mototRun(Motors.M1, Dir.CW, 30)
    basic.pause(500)
    DFRobotMaqueenPlus.mototRun(Motors.M2, Dir.CW, 30)
    DFRobotMaqueenPlus.mototRun(Motors.M1, Dir.CCW, 30)
    basic.pause(500)
    DFRobotMaqueenPlus.mototRun(Motors.M1, Dir.CW, 255)
    DFRobotMaqueenPlus.mototRun(Motors.M2, Dir.CCW, 255)
    basic.pause(1430)
    DFRobotMaqueenPlus.mototRun(Motors.ALL, Dir.CW, 100)
    basic.pause(200)
    DFRobotMaqueenPlus.mototStop(Motors.ALL)
    basic.showIcon(IconNames.Skull)
    basic.pause(10000000)
})
