DFRobotMaqueenPlus.I2CInit()
basic.forever(function () {
    DFRobotMaqueenPlus.setRGBLight(RGBLight.RGBL, Color.CYAN)
    basic.pause(850)
    DFRobotMaqueenPlus.setRGBLight(RGBLight.RGBL, Color.OFF)
    DFRobotMaqueenPlus.setRGBLight(RGBLight.RGBR, Color.YELLOW)
    basic.pause(850)
    DFRobotMaqueenPlus.setRGBLight(RGBLight.RGBR, Color.OFF)
    DFRobotMaqueenPlus.setRGBLight(RGBLight.RGBL, Color.PINK)
    basic.pause(850)
    DFRobotMaqueenPlus.setRGBLight(RGBLight.RGBL, Color.OFF)
    DFRobotMaqueenPlus.setRGBLight(RGBLight.RGBR, Color.GREEN)
    basic.pause(850)
    DFRobotMaqueenPlus.setRGBLight(RGBLight.RGBR, Color.OFF)
})
basic.forever(function () {
    DFRobotMaqueenPlus.mototRun(Motors.M1, Dir.CCW, 40)
    DFRobotMaqueenPlus.mototRun(Motors.M2, Dir.CCW, 40)
    basic.pause(500)
    DFRobotMaqueenPlus.mototRun(Motors.M2, Dir.CW, 30)
    DFRobotMaqueenPlus.mototRun(Motors.M1, Dir.CCW, 30)
    basic.pause(500)
    DFRobotMaqueenPlus.mototRun(Motors.M2, Dir.CCW, 40)
    DFRobotMaqueenPlus.mototRun(Motors.M1, Dir.CCW, 40)
    basic.pause(500)
    DFRobotMaqueenPlus.mototRun(Motors.M1, Dir.CW, 30)
    DFRobotMaqueenPlus.mototRun(Motors.M2, Dir.CCW, 30)
    basic.pause(500)
})
